{
    "formData": {
        "entityType": "Department",
        "formCategory": "FF",
        "formName": "Purchase Order",
        "frequency": "any",
        "editable": 1,
        "deletable": 1,
        "newRec": 1,
        "parentID": 0
    },
    "fieldsData": [
        {
            "data_name": "PO_ID",
            "data_type": "sequence",
            "sorting_value": "1",
            "identifier": 0,
            "options_from": "",
            "fetch_function": "",
            "calculation": "",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "readonly",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 1,
            "sumClass": "",
            "data_info": "",
            "help_text": "",
            "sum_func": "",
            "countIf": "",
            "decimals": "0",
            "prefix": "PO",
            "sufix": "",
            "digits": "5",
            "replacer": "0",
            "start_with": "1"
        },
        {
            "data_name": "Vendor",
            "data_type": "options",
            "sorting_value": "2",
            "identifier": 0,
            "options_from": "VendorEntity",
            "fetch_function": "",
            "calculation": "",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "required",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 0,
            "sumClass": "",
            "data_info": "",
            "help_text": "",
            "sum_func": "",
            "countIf": "",
            "decimals": "",
            "formName": "Vendors"
        },
        {
            "data_name": "Item",
            "data_type": "options",
            "sorting_value": "3",
            "identifier": 0,
            "options_from": "ItemEntity",
            "fetch_function": "",
            "calculation": "",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "required",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 0,
            "sumClass": "",
            "data_info": "",
            "help_text": "",
            "sum_func": "",
            "countIf": "",
            "decimals": "",
            "formName": "Items"
        },
        {
            "data_name": "Quantity",
            "data_type": "number",
            "sorting_value": "4",
            "identifier": 0,
            "options_from": "",
            "fetch_function": "",
            "calculation": "",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "required",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 0,
            "sumClass": "",
            "data_info": "",
            "help_text": "",
            "sum_func": "",
            "countIf": "",
            "decimals": "0"
        },
        {
            "data_name": "Price",
            "data_type": "number",
            "sorting_value": "5",
            "identifier": 0,
            "options_from": "",
            "fetch_function": "",
            "calculation": "",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "required",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 0,
            "sumClass": "",
            "data_info": "",
            "help_text": "",
            "sum_func": "",
            "countIf": "",
            "decimals": "2"
        },
        {
            "data_name": "TotalPrice",
            "data_type": "calculation",
            "sorting_value": "6",
            "identifier": 0,
            "options_from": "",
            "fetch_function": "",
            "calculation": "{QR^Quantity^QR.Item,Purchase Order.Item,=} * {Purchase Order.Price}",
            "defaultVal": "",
            "features": "",
            "inherit": 0,
            "attributes": "readonly",
            "entityMethod": "",
            "entityOrLevel": "",
            "mapping": [],
            "keyMember": 0,
            "sumClass": "total",
            "data_info": "",
            "help_text": "",
            "sum_func": "SUM",
            "countIf": "",
            "decimals": "2"
        }
    ]
}